### ISSUE TITLE
Could you provide a short Readme?

### ISSUE THREAD

**Issue by DaHu4wA** [dritonshoshi/n-sysmon#1]
Hy guys!
I want to include N-Sysmon in a new project (which uses Spring Boot, Spring Data JPA etc).

What do I have to do? Is there a public Maven artefact for this framework?

Could you maybe provide a short Readme.md file?

Best regards,
Stefan Huber.

**Comment by dritonshoshi** [comment]
Hi Stefan,

we will provide soon a README. Thanks for that hint. 

Best regards,
NSysmon Team
